default: &default
  encoding: unicode
  adapter: postgresql
  host: <%= ENV.fetch("DATABASE_HOST") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  timeout: 5000
  

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE") %>
